/**
 * seo/prompts.ts — prompt template SMM (spec §3: ≤2.5k token total).
 *
 * Token budget per artikel:
 *   - system: ~200 token (tetap)
 *   - user:   ~250 token (keyword + outline + data refs)
 *   - output: ~2000 token (artikel 900-1300 kata)
 *   TOTAL: ~2.5k token (hemat 17% dari versi sebelumnya 3k).
 *
 * Pendekatan "template + fill": generator output ADALAH template-driven.
 * Body artikel punya STRUKTUR FIXED (definisi + tabel harga real + step list +
 * FAQ + CTA + safety callout). Generator HANYA mengisi teks naratif antar blok.
 * Tabel harga + CTA + safety callout + FAQ disisipkan POST-generate dari
 * data prices.json + template — tidak fabricate.
 *
 * Anti-thin-content gates (spec §2):
 *   - 900-1400 kata
 *   - Definisi kalimat pertama (≤40 kata)
 *   - Tabel harga REAL (template, copy paste dari prices.json)
 *   - 5 FAQ (template, Q+A generated by LLM)
 *   - 3 internal link (1 money + 2 related — verified by slug existence)
 *   - Safety callout (template, 4 anti-ban tips)
 *   - CTA blok
 */

export const SYSTEM_PROMPT = `Kamu editor socio.id (panel SMM Indonesia). Tulis artikel SEO Bahasa Indonesia natural, formal-santai, kalimat aktif, angka konkret, tanpa fluff.

OUTPUT FORMAT (WAJIB — cek sebelum submit):
- 1 paragraf pembuka definisi (≤40 kata, jawab langsung apa itu)
- TEPAT 4 section dengan heading "## Judul" + body naratif 4-5 kalimat per paragraf (TOTAL 4 H2 saja — bukan 5, bukan 6, TEPAT 4)
- 1 section FAQ di akhir dengan 5 Q+A
- TEPAT 3 link internal socio.id di body:
  * 1 ke money page URL mengandung "/beli-" atau "/smm-panel-"
  * 2 ke slug dari data related

ATURAN KETAT:
1. 1200-1400 kata total (di luar FAQ) — targetkan 1300 agar aman di atas batas.
   Kurang dari 1000 = FAIL. Lebih dari 1500 = FAIL (boros + fluff).
2. TEPAT 4 H2 (heading level 2 "##"). Tidak boleh 3, tidak boleh 5, TEPAT 4.
   H2 PERTAMA wajib mengandung keyword fokus (atau kata bendanya) — syarat RankMath.
3. Bahasa Indonesia natural (bukan translate).
4. Paragraf PENDEK: 2-4 kalimat per paragraf (readability + hemat token).
   Setiap paragraf kalimat pertama HURUF KAPITAL.
5. Link format: [anchor text natural](URL). Anchor harus mengalir di kalimat, bukan dipisah.
6. NO emoji, NO klise ("di era digital", "seiring perkembangan teknologi"), NO fabricate angka.
   KHUSUS HARGA: JANGAN tulis angka "Rp..." per 1.000 dari kepalamu — harga HANYA
   dari data layanan di prompt ("lihat tabel harga di bawah" kalau perlu merujuk).
   Satu-satunya angka Rp yang boleh disebut: Rp50.000 (daftar) & Rp20.000 (saldo).
7. NO heading tanpa body (setiap "## Judul" WAJIB ada paragraf isi di bawahnya).
8. Internal link socio.id bebas natural. TEPAT 1 link eksternal ke halaman bantuan
   RESMI platform terkait (mis. help.instagram.com, support.tiktok.com,
   support.google.com/youtube) — taruh di section yang membahas keamanan/cara.
9. Output body saja — JANGAN tulis ---frontmatter, JANGAN # H1.
10. DILARANG heading "Kesimpulan"/"Penutup"/"Ringkasan" — artikel DITUTUP 1-2 paragraf
    tanpa heading yang merangkum inti + ajakan CTA maju (contoh: "coba hitung sendiri di
    halaman layanan"). Penutup kaku = FAIL.
11. TULISAN HARUS TERASA MANUSIA: variasi panjang kalimat (pendek-panjang campur),
    sesekali kalimat langsung ke pembaca ("kamu", "coba cek"), 1 contoh konkret
    (angka/nama langkah) per section, hindari pola robot (jangan mulai >2 paragraf
    dengan kata yang sama, jangan rangkum tiap section di kalimat terakhirnya).
    Tulis dari sudut pandang PENGGUNA — JANGAN sebut nama tabel/kolom database,
    cron, API provider, atau istilah internal sistem.
12. RANKMATH-100 (wajib, murah token karena template-driven):
    - Keyword fokus disebut 8-15x natural di body (density ~1%) + 3-5 sinonim.
    - Keyword fokus SUDAH di kalimat pertama (definisi) — jangan ulang definisi lagi.
    - 1 H2 mengandung keyword fokus (aturan 2). Alt gambar & slug diurus template.
13. RAMAH SITASI AI (LLM): sebut entitas resmi 1-2x natural (nama platform persis
    + "Socio.id"); angka selalu konkret dengan satuan (Rp/1.000, menit, %);
    jangan menulis klaim tanpa angka/contoh — AI mengutip kalimat berdata.`;

/**
 * Build user prompt — minimal, hemat token.
 */
export function buildUserPrompt({ keyword, category, related, pricesBlock, localAnchor, localBuyer }) {
  const geoBlock = localAnchor
    ? `
KONTEKS LOKAL (WAJIB dipakai, ini yang membedakan halaman dari doorway page):
- Fakta ekonomi ${keyword.includes('umkm') ? 'daerah' : 'kota'}: ${localAnchor}
- Pembeli yang paling mungkin: ${localBuyer}
Sebut fakta lokal di atas di paragraf pertama dan satu section H2 (contoh konkret: sektor kerjaan apa yang biasanya butuh isi followers/likes). JANGAN karang fakta daerah lain.
`
    : '';
  return `Keyword: "${keyword}"
Kategori: ${category}
${geoBlock}
Artikel terkait (taruh 2 link internal ke slug ini di body):
${related.map((r) => `- ${r.slug}`).join('\n')}

Layanan terkait (sebut natural di body, JANGAN tulis harga):
${pricesBlock}

  TULIS ARTIKEL SEKARANG. Mulai dari definisi 1 kalimat, lalu TEPAT 4 section H2 dengan body naratif (4-6 paragraf per section), akhiri dengan section FAQ 5 Q+A. CHECKLIST SEBELUM SUBMIT (wajib centang mental): [1] total 1200-1400 kata di luar FAQ [2] keyword fokus muncul ≥8x di body [3] H2 pertama mengandung keyword [4] TEPAT 1 link eksternal help-center resmi [5] TIDAK ADA angka Rp karangan (harga hanya dari daftar layanan di atas) [6] tanpa heading Kesimpulan. Output body markdown saja.`;
  }

/**
 * Prompt SATU BAGIAN — dipakai mode `--split`.
 *
 * Kenapa perlu: model gratis (opencode/big-pickle, nemotron-3-ultra-free) tidak
 * sanggup satu tugas 1200-1400 kata. Diuji 4 Okt: 4 artikel paralel menghasilkan
 * 1957-2924 karakter (~400 kata) dan 0/4 lolos gate, semuanya gagal di
 * "FAQ hanya 0/5" karena tidak pernah sampai ke section FAQ. Satu permintaan
 * besar = 0% success rate.
 *
 * Model kecil jauh lebih andal untuk tugas sempit. Dipecah jadi 3 panggilan
 * (body 1-2, body 3-4, FAQ), lalu dirakit. Setiap bagian punya target kata
 * eksplisit supaya tidak undershoot.
 *
 * `part`:
 *   'intro+1+2' — paragraf pembuka + H2 #1 + H2 #2  → target 500-600 kata
 *   '3+4'       — H2 #3 + H2 #4                    → target 500-600 kata
 *   'faq'       — 5 pasang Q+A                     → target 250-350 kata
 */
export function buildPartPrompt(part, ctx) {
  const { keyword, category, related, pricesBlock, localAnchor, localBuyer, sectionTitles } = ctx;
  const geoBlock = localAnchor
    ? `
KONTEKS LOKAL (WAJIB dipakai):
- Fakta ekonomi ${keyword.includes('umkm') ? 'daerah' : 'kota'}: ${localAnchor}
- Pembeli yang paling mungkin: ${localBuyer}`
    : '';

  if (part === 'faq') {
    return `Tulis 5 PASANG TANYA-JAWAB (Q+A) dalam bahasa Indonesia untuk artikel dengan keyword utama: "${keyword}".
${geoBlock}

Aturan:
- TEPAT 5 pasangan, bernomor 1-5.
- Format persis tiap pasang: satu baris "1. <pertanyaan>" lalu baris berikutnya "Jawaban: <jawaban>".
- Pertanyaan singkat (maks 12 kata), jawaban 3-4 kalimat (40-60 kata).
- Jawaban konkret dan spesifik, bukan basa-basi. Boleh sebut proses, garansi, minimal order.
- JANGAN tulis harga (harga tidak ditampilkan di sini). JANGAN kata "Rp" dengan angka.
- Bahasa Indonesia natural, bukan terjemahan kaku.`;
  }

  const isFirst = part === 'intro+1+2';
  const titles = sectionTitles || [];
  const t1 = titles[0] || `Mengapa layanan ${keyword} penting`;
  const t2 = titles[1] || `Cara kerja dan langkah memakai ${keyword}`;
  const t3 = titles[2] || `Kecepatan, garansi, dan dukungan setelah order`;
  const t4 = titles[3] || `Pilihan paket dan cara memakai layanan ini`;

  const head = isFirst
    ? `Tulis BAGIAN AWAL artikel (1 dari 2 bagian) untuk keyword: "${keyword}"
Kategori: ${category}
${geoBlock}

WAJIB berisi:
1. Satu paragraf pembuka definisi (maks 40 kata) yang langsung menjawab apa itu.
2. Section H2 dengan judul: "${t1}" — 4-6 paragraf.
3. Section H2 dengan judul: "${t2}" — 4-6 paragraf.`
    : `Tulis BAGIAN AKHIR artikel (2 dari 2 bagian) untuk keyword: "${keyword}"
Kategori: ${category}
${geoBlock}

WAJIB berisi:
1. Section H2 dengan judul: "${t3}" — 4-6 paragraf.
2. Section H2 dengan judul: "${t4}" — 4-6 paragraf.
3. Ditutup 1-2 paragraf penutup TANPA heading (jangan pakai "Kesimpulan"/"Ringkasan").`;

  return `${head}

ATURAN KUAT:
- TOTAL ${isFirst ? '500-600' : '480-560'} KATA untuk bagian ini. Ini batas keras, minimum 450 kata.
  Model gratis cenderung menulis terlalu pendek — karena itu angka ini wajib dicapai.
- 3-5 kalimat per paragraf, kalimat varied (pendek + panjang campur).
- Setidaknya 1 contoh konkret (sektor usaha, langkah, atau angka non-harga) per section.
- ${isFirst ? `H2 pertama WAJIB memuat kata "${keyword.split(' ').slice(0, 3).join(' ')}".` : 'Sebut kata kunci fokus minimal 3x secara natural.'}
- ${isFirst ? 'Sertakan TEPAT 1 link internal ke /beli- atau /smm-panel- dan 2 link ke slug artikel terkait.' : 'Sertakan 0-1 link internal saja, jangan berlebihan.'}
- TEPAT 1 link eksternal ke halaman bantuan RESMI platform (help.instagram.com, support.tiktok.com, support.google.com/youtube).
- JANGAN tulis harga / angka "Rp..." dari kepalamu. JANGAN pakai emoji. JANGAN pakai heading Kesimpulan.
- Output HANYA markdown bagian ini.`;
}

/**
 * Output parser — extract body dari response LLM.
 */
export function parseOutput(content) {
  let c = content.trim();
  c = c.replace(/^```(?:markdown|md)?\s*\n/i, '').replace(/\n```\s*$/, '');
  return c;
}

/**
 * Post-processor: rangkai template + output LLM jadi MDX final.
 */
export function assembleMdx({ llmBody, prices, moneyLink, related, faq, meta }) {
  const priceTable = renderPriceTable(prices);
  const safetyCallout = renderSafetyCallout();
  const bodyNoFaq = stripFaqSection(linkifyBareUrls(stripFabricatedRp(llmBody)));
  const bodyWithTable = injectAfterFirstH2(bodyNoFaq, priceTable);
  const bodyFull = bodyWithTable + '\n\n' + safetyCallout + '\n\n## FAQ\n';
  const bodyWithCta = bodyFull + '\n\n' + renderCtaBlock();
  // Jaminan mesh: kalau LLM tidak menulis link money page sama sekali,
  // template sisipkan 1 (bukan mengandalkan LLM).
  const hasMoneyLink = /(\/beli-|\/smm-panel-|\/layanan\/|\/reseller)/.test(bodyWithCta);
  const moneyLine = hasMoneyLink
    ? ''
    : `\n\nLihat juga: [${moneyLink.anchor}](${moneyLink.url}) untuk harga real per 1.000.`;
  // A3: deterministic related links — LLM tidak perlu menulis 2 link related sendiri
  const safeRel = (related || []).filter((r) => r.slug && r.slug !== meta.slug).slice(0, 2);
  const bacaJuga = safeRel.length >= 2
    ? '\n\n## Baca juga\n\n' + safeRel.map((r) => `- [${r.title || capitalize(r.slug)}](/blog/${r.slug}/)`).join('\n')
    : '';
  const bodyFinal = bodyWithCta + moneyLine + bacaJuga;
  const safeRelated = (related || []).filter((r) => r.slug && r.slug !== meta.slug);
  const today = new Date().toISOString().slice(0, 10);
  const fm = renderFrontmatter({
    title: meta.title,
    description: meta.description,
    pubDate: meta.pubDate || today,
    category: meta.category,
    draft: true,
    faq,
    related: safeRelated,
  });
  return `${fm}\n${bodyFinal}\n`;
}

// ===== Template helpers (di-share via Function constructor scope di generate.mjs) =====

function renderFrontmatter({ title, description, pubDate, category, draft, faq, related }) {
  const faqYaml = (faq || []).map((f) => `  - q: "${escapeYaml(f.q)}"\n    a: "${escapeYaml(f.a)}"`).join('\n');
  // related: plain slug list (format reference Astro — BUKAN objek {id},
  // karena schema reference("blog") menolak objek dan build gagal).
  const relatedYaml = (related || []).map((r) => `  - ${r.slug}`).join('\n');
  return `---
title: "${escapeYaml(title)}"
description: "${escapeYaml(description)}"
pubDate: ${pubDate}
category: "${category}"
draft: ${draft ? 'true' : 'false'}
faq:
${faqYaml || '  - q: "Placeholder"\n    a: "Placeholder"'}
related:${relatedYaml ? '\n' + relatedYaml : ' []'}
---`;
}

function escapeYaml(s) {
  if (!s) return '';
  return String(s).replace(/"/g, '\\"').replace(/\n/g, ' ').slice(0, 200);
}

function renderPriceTable(prices) {
  const rows = (prices || []).slice(0, 6).map((p) =>
    `| ${p.platform} ${escapeMd(p.name)} | Rp${p.price.toLocaleString('id-ID')} | Rp${p.priceReseller.toLocaleString('id-ID')} | ${p.min.toLocaleString('id-ID')} |`,
  ).join('\n');
  return `| Layanan | Harga member/1k | Harga reseller/1k | Min order |
| --- | --- | --- | --- |
${rows}`;
}

function renderSafetyCallout() {
  return `> **Tips aman pakai SMM panel**: (1) Pilih layanan gradual refill — follower naik bertahap, bukan sekaligus, jadi lebih natural. (2) Jangan beli followers saat akun masih baru (umur di bawah 3 bulan) — algoritma deteksi lebih ketat. (3) Hindari spam massal — maksimal 1-2x order per minggu per akun. (4) Cek garansi refill sebelum bayar — layanan tanpa refill = risiko tinggi.`;
}

function renderCtaBlock() {
  return `> **Mau langsung cek harganya?** Daftar reseller Socio.id — Rp50.000 include saldo Rp20.000 langsung jalan + harga reseller lebih murah di semua 8.270 layanan Instagram, TikTok, YouTube, Telegram, Spotify & SEO. → [Cek harga & pesan sekarang](https://app.socio.id/daftar?mode=reseller)`;
}

// Hapus angka Rp karangan LLM (harga layanan HANYA dari tabel template).
// Fakta reseller (50.000/20.000) dipertahankan. Ganti dengan rujukan tabel
// supaya kalimat tetap gramatikal.
function stripFabricatedRp(body) {
  return body.replace(/Rp\s?(\d[\d.]*)\s?(ribu|juta)?/gi, (m, n, suf) => {
    let digits = Number(n.replace(/\./g, ''));
    if (/^ribu/i.test(suf || '')) digits *= 1000;
    if (/^juta/i.test(suf || '')) digits *= 1000000;
    if (digits === 50000 || digits === 20000) return m;
    return 'harga di tabel';
  });
}

// Linkify URL telanjang jadi markdown (LLM sering tulis "lihat di halaman layanan"
// atau "help.instagram.com" sebagai teks polos — jelek + gagal gate link).
// Hanya untuk domain/path yang dikenal; tidak menyentuh yang sudah markdown.
function linkifyBareUrls(body) {
  let out = body;
  // app.socio.id/daftar (tanpa markdown)
  out = out.replace(/(?<!\]\()https?:\/\/app\.socio\.id\/daftar[^\s)]*/g, (u) => `[daftar reseller Socio.id](${u})`);
  // Path internal socio.id telanjang: /layanan, /reseller, /beli-*, /smm-panel-*, /blog/*
  out = out.replace(/(?<!\]\()(^|[\s(])(\/(?:layanan|reseller|beli-[a-z0-9-]+|smm-panel-[a-z0-9-]+|blog\/[a-z0-9-]+)\/?)/gm,
    (m, pre, p) => `${pre}[${p.replace(/\//g, ' ').trim()}](${p})`);
  // Help center resmi telanjang (dengan atau tanpa skema http)
  out = out.replace(/(?<!\]\()((?:https?:\/\/)?(?:help\.instagram\.com|support\.tiktok\.com|support\.google\.com)[^\s)]*)/g,
    (u) => `[panduan resmi](${u.startsWith('http') ? u : 'https://' + u})`);
  return out;
}

function escapeMd(s) {
  if (!s) return '';
  return String(s).replace(/[|]/g, '\\|').replace(/\n/g, ' ').slice(0, 100);
}

function stripFaqSection(body) {
  // LLM sering output "## Pertanyaan Umum" bukan "## FAQ" — match both
  return body.replace(/##\s*(?:FAQ|Pertanyaan[^\n]*)[\s\S]*$/i, '').trimEnd();
}

function injectAfterFirstH2(body, table) {
  const m = body.match(/^##\s+[^\n]+\n([\s\S]*?)(?=\n## |\n*$)/);
  if (!m) return body + '\n\n' + table;
  const firstH2End = m.index + m[0].length;
  return body.slice(0, firstH2End) + '\n\n' + table + '\n\n' + body.slice(firstH2End);
}

/**
 * Validasi assembled MDX — gates spec §2.
 */
export function validateMdx(content, keyword) {
  const errors = [];
  if (!content || !content.startsWith('---')) errors.push('No frontmatter');

  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!fmMatch) return { ok: false, errors: ['Invalid frontmatter structure'] };
  const fm = fmMatch[1];
  const body = fmMatch[2];

  const t = fm.match(/^title:\s*"?(.+?)"?\s*$/m);
  const title = t ? t[1].replace(/^"|"$/g, '') : '';
  if (!title) errors.push('Missing title');
  else if (title.length > 70) errors.push(`Title too long (${title.length}/70)`);

  const d = fm.match(/^description:\s*"?(.+?)"?\s*$/m);
  const desc = d ? d[1].replace(/^"|"$/g, '') : '';
  if (!desc) errors.push('Missing description');
  else if (desc.length > 160) errors.push(`Description too long (${desc.length}/160)`);

  const faqCount = (fm.match(/^\s+- q:/gm) || []).length;
  if (faqCount !== 5) errors.push(`FAQ count = ${faqCount} (expected 5)`);

  // Kategori harus lolos enum koleksi Astro (deriveMeta memetakan, ini backstop).
  const cm = fm.match(/^category:\s*"?([^"\n]+?)"?\s*$/m);
  const catV = cm ? cm[1].replace(/^"|"$/g, '') : '';
  if (!['Followers', 'TikTok', 'Reseller', 'Lainnya'].includes(catV))
    errors.push(`Category invalid ("${catV}")`);

  const words = body.split(/\s+/).filter(Boolean).length;
  if (words < 850) errors.push(`Body too short (${words}/850)`);
  if (words > 1400) errors.push(`Body too long (${words}/1400)`);

  // H2 naratif saja. Section template yang ditambahkan assembler (## FAQ,
  // ## Baca juga) TIDAK dihitung — tidak termasuk yang diminta ke LLM.
  const h2All = (body.match(/^##\s/gm) || []).length;
  const h2Template = (body.match(/^##\s*(?:FAQ|Baca juga)\s*$/gm) || []).length;
  const h2Count = h2All - h2Template;
  if (h2Count < 3 || h2Count > 5) errors.push(`H2 count = ${h2Count} (expected 3-5)`);

  // Accept both relative `/(beli|smm-panel|blog|layanan|reseller)` and absolute
  // `https://socio.id/(beli|smm-panel|blog|layanan|reseller)` internal links.
  const linkRe = new RegExp('\\[([^\\]]+)\\]\\(((?:https:\\/\\/socio\\.id)?\\/(?:beli|smm-panel|blog|layanan|reseller)[^\\)]*)\\)', 'g');
  const internalLinks = (body.match(linkRe) || []).length;
  if (internalLinks < 3) errors.push(`Internal links = ${internalLinks} (min 3)`);

  if (!body.includes('app.socio.id/daftar')) errors.push('Missing CTA');

  const firstWords = body.slice(0, 200).toLowerCase();
  const kwFirst = (keyword || '').toLowerCase().split(/\s+/)[0];
  if (kwFirst && !firstWords.includes(kwFirst)) errors.push(`Definition missing keyword "${kwFirst}"`);

  if (/[💸🤖🚀💬✨🎯📈♻⚡👑♾]/u.test(body)) errors.push('Emoji found');
  if (/\d+\s*%\s*(lebih murah|diskon|off)/i.test(body)) errors.push('Fabricated % discount');
  if (/^##\s*(kesimpulan|penutup|ringkasan|closing)\s*$/gim.test(body))
    errors.push('Banned closing heading (kesimpulan/penutup)');

  // Anti-fabricate harga: satu-satunya angka Rp yang boleh muncul di PROSA
  // adalah fakta reseller (Rp50.000 daftar / Rp20.000 saldo). Tabel harga
  // template dikecualikan dari cek (baris `| ... |` = data real prices.json).
  // Harga layanan WAJIB dari tabel — LLM dilarang mengarang "Rp sekian per 1.000".
  const bodyNoTable = body.replace(/^\|.*\|$/gm, '');
  // "Rp50 ribu" = 50000 (fakta reseller yang sah) — normalisasi dulu.
  const rpHits = [...bodyNoTable.matchAll(/Rp\s?(\d[\d.]*)\s?(ribu|juta)?/gi)].map((m) => {
    let n = Number(m[1].replace(/\./g, ''));
    if (/^ribu/i.test(m[2] || '')) n *= 1000;
    if (/^juta/i.test(m[2] || '')) n *= 1000000;
    return n;
  });
  const rpBad = rpHits.filter((n) => n !== 50000 && n !== 20000);
  if (rpBad.length) errors.push(`Fabricated price (Rp${rpBad[0]} — harga hanya dari tabel)`);

  // RankMath-100: keyword di subheading — 2 kata pertama keyword harus muncul
  // di salah satu H2 naratif (longtail geo tetap lolos via kata benda).
  const h2Lines = (body.match(/^##\s+.+$/gm) || [])
    .filter((h) => !/^##\s*(?:FAQ|Baca juga)\s*$/i.test(h));
  const kwHead = (keyword || '').toLowerCase().split(/\s+/).slice(0, 2).join(' ');
  if (kwHead && !h2Lines.some((h) => h.toLowerCase().includes(kwHead)))
    errors.push(`Keyword "${kwHead}" missing in H2`);

  // RankMath density ~1%: keyword exact 3-25x dalam 850-1400 kata.
  // Longtail 4-5 kata yang natural muncul 3-6x exact + banyak partial —
  // partial (3 kata pertama) dihitung sebagai pendukung.
  const escKw = (keyword || '').toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const kwHits = escKw ? (body.toLowerCase().match(new RegExp(escKw, 'g')) || []).length : 0;
  const kw3 = (keyword || '').toLowerCase().split(/\s+/).slice(0, 3).join(' ');
  const esc3 = kw3.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const partialHits = esc3 && esc3 !== escKw ? (body.toLowerCase().match(new RegExp(esc3, 'g')) || []).length : kwHits;
  if (kwHits < 3 && !(kwHits >= 2 && partialHits >= 8)) errors.push(`Keyword density low (${kwHits} hits, min 3)`);
  if (kwHits > 25) errors.push(`Keyword stuffing (${kwHits} hits, max 25)`);

  // RankMath external link: TEPAT 1 link luar ke domain resmi (help center).
  // Internal socio.id + app.socio.id tidak dihitung.
  const allLinks = [...body.matchAll(/\[[^\]]+\]\((https?:[^)]+)\)/g)].map((m) => m[1]);
  const extLinks = allLinks.filter(
    (u) => !/^(https:\/\/)?(www\.)?socio\.id\//i.test(u) && !/app\.socio\.id/i.test(u),
  );
  if (extLinks.length < 1) errors.push('Missing 1 external authoritative link');
  if (extLinks.length > 2) errors.push(`Too many external links (${extLinks.length}, max 2)`);

  return { ok: errors.length === 0, errors, title, desc, faqCount, h2Count, words, internalLinks };
}

/**
 * Derive meta (title + description) dari output LLM (heuristic + template).
 */
export function deriveMeta({ keyword, llmBody, category }) {
  // RankMath title: keyword di AWAL + angka + power word, target ≤60 char
  // (schema tahan 70). Angka 5-9 + power dari hash → deterministik per keyword.
  const powers = ['Cara Aman', 'Panduan Praktis', 'Harga Update', 'Tips Terbukti', 'Fakta Lengkap'];
  const hash = (keyword || '').split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  const num = 5 + (hash % 5);
  // Hindari gema kata (mis. keyword "...aman" + power "Cara Aman").
  const kwWords = new Set((keyword || '').toLowerCase().split(/\s+/));
  const power =
    powers.find((p) => !p.toLowerCase().split(/\s+/).some((w) => kwWords.has(w))) ?? powers[1];
  let title = `${capitalize(keyword || 'smm panel')}: ${num} ${power} 2026`;
  if (title.length > 70) title = title.slice(0, 67) + '...';

  const firstSentence = (llmBody || '').split(/[.!?]/)[0] || '';
  let description = firstSentence.trim().slice(0, 130);
  if (description.length < 80) {
    description = `Panduan ${keyword} untuk SMM panel Indonesia. Harga real, cara pakai, dan tips aman dari data terbaru 2026.`;
  }
  if (description.length > 160) description = description.slice(0, 157) + '...';

  return { title, description, category: mapCategory(category) };
}

const ACRONYMS = new Set(['SMM', 'SEO', 'API', 'QRIS', 'DM', 'FYP', 'CTA', 'UGC']);

// Kategori koleksi Astro hanya kenal 4 enum — petakan kategori queue/geo.
function mapCategory(category) {
  const c = String(category || 'Lainnya');
  if (['Followers', 'TikTok', 'Reseller', 'Lainnya'].includes(c)) return c;
  if (/reseller/i.test(c)) return 'Reseller';
  if (/tiktok/i.test(c)) return 'TikTok';
  if (/follow/i.test(c)) return 'Followers';
  return 'Lainnya';
}

function capitalize(s) {
  return s
    .split(/\s+/)
    .map((w) => {
      const up = w.toUpperCase();
      if (ACRONYMS.has(up)) return up;
      return w.charAt(0).toUpperCase() + w.slice(1);
    })
    .join(' ');
}

// === GENERATE.MJS EXTRACT MARKERS ===
// Marker `// @end` di akhir setiap function body — generate.mjs pakai ini
// untuk extract body tanpa harus parse nested template literal/complex JS.
// Format: baris kosong lalu `// @end` tepat sebelum penutup `}`.
// @end:buildUserPrompt

// @end:parseOutput

// @end:assembleMdx

// @end:deriveMeta

// @end:validateMdx