/**
 * seo/prompts.ts — prompt template SMM (spec §3: ≤2.5k token total).
 *
 * Token budget per artikel:
 *   - system: ~200 token (tetap)
 *   - user:   ~250 token (keyword + outline + data refs)
 *   - output: ~2000 token (artikel 900-1300 kata)
 *   TOTAL: ~2.5k token (hemat 17% dari versi sebelumnya 3k).
 *
 * Pendekatan "template + fill": generator output ADALAH template-driven.
 * Body artikel punya STRUKTUR FIXED (definisi + tabel harga real + step list +
 * FAQ + CTA + safety callout). Generator HANYA mengisi teks naratif antar blok.
 * Tabel harga + CTA + safety callout + FAQ disisipkan POST-generate dari
 * data prices.json + template — tidak fabricate.
 *
 * Anti-thin-content gates (spec §2):
 *   - 900-1400 kata
 *   - Definisi kalimat pertama (≤40 kata)
 *   - Tabel harga REAL (template, copy paste dari prices.json)
 *   - 5 FAQ (template, Q+A generated by LLM)
 *   - 3 internal link (1 money + 2 related — verified by slug existence)
 *   - Safety callout (template, 4 anti-ban tips)
 *   - CTA blok
 */

export const SYSTEM_PROMPT = `Kamu editor socio.id (panel SMM Indonesia). Tulis artikel SEO Bahasa Indonesia natural, formal-santai, kalimat aktif, angka konkret, tanpa fluff.

OUTPUT FORMAT (WAJIB — cek sebelum submit):
- 1 paragraf pembuka definisi (≤40 kata, jawab langsung apa itu)
- TEPAT 4 section dengan heading "## Judul" + body naratif 4-5 kalimat per paragraf (TOTAL 4 H2 saja — bukan 5, bukan 6, TEPAT 4)
- 1 section FAQ di akhir dengan 5 Q+A
- TEPAT 3 link internal socio.id di body:
  * 1 ke money page URL mengandung "/beli-" atau "/smm-panel-"
  * 2 ke slug dari data related

ATURAN KETAT:
1. 1000-1200 kata total (di luar FAQ). Lebih dari 1200 = FAIL. Kurang dari 1000 = FAIL.
2. TEPAT 4 H2 (heading level 2 "##"). Tidak boleh 3, tidak boleh 5, TEPAT 4.
3. Bahasa Indonesia natural (bukan translate).
4. Setiap paragraf kalimat pertama HURUF KAPITAL.
5. Link format: [anchor text natural](URL). Anchor harus mengalir di kalimat, bukan dipisah.
6. NO emoji, NO klise ("di era digital", "seiring perkembangan teknologi"), NO fabricate angka.
7. NO heading tanpa body (setiap "## Judul" WAJIB ada paragraf isi di bawahnya).
8. NO link luar socio.id (kecuali FAQ/CTA).
9. Output body saja — JANGAN tulis ---frontmatter, JANGAN # H1.`;

/**
 * Build user prompt — minimal, hemat token.
 */
export function buildUserPrompt({ keyword, category, related, pricesBlock }) {
  return `Keyword: "${keyword}"
Kategori: ${category}

Artikel terkait (taruh 2 link internal ke slug ini di body):
${related.map((r) => `- ${r.slug}`).join('\n')}

Layanan terkait (sebut natural di body, JANGAN tulis harga):
${pricesBlock}

TULIS ARTIKEL SEKARANG. Mulai dari definisi 1 kalimat, lalu 3-5 section H2 dengan body naratif, akhiri dengan section FAQ 5 Q+A. Output body markdown saja.`;
}

/**
 * Output parser — extract body dari response LLM.
 */
export function parseOutput(content) {
  let c = content.trim();
  c = c.replace(/^```(?:markdown|md)?\s*\n/i, '').replace(/\n```\s*$/, '');
  return c;
}

/**
 * Post-processor: rangkai template + output LLM jadi MDX final.
 */
export function assembleMdx({ llmBody, prices, moneyLink, related, faq, meta }) {
  const priceTable = renderPriceTable(prices);
  const safetyCallout = renderSafetyCallout();
  const bodyNoFaq = stripFaqSection(llmBody);
  const bodyWithTable = injectAfterFirstH2(bodyNoFaq, priceTable);
  const bodyFull = bodyWithTable.replace(/(## FAQ|^FAQ)/im, `${safetyCallout}\n\n## FAQ`);
  const bodyWithCta = bodyFull + '\n\n' + renderCtaBlock();
  const safeRelated = (related || []).filter((r) => r.slug && r.slug !== meta.slug);
  const today = new Date().toISOString().slice(0, 10);
  const fm = renderFrontmatter({
    title: meta.title,
    description: meta.description,
    pubDate: meta.pubDate || today,
    category: meta.category,
    draft: true,
    faq,
    related: safeRelated,
  });
  return `${fm}\n${bodyWithCta}\n`;
}

// ===== Template helpers (di-share via Function constructor scope di generate.mjs) =====

function renderFrontmatter({ title, description, pubDate, category, draft, faq, related }) {
  const faqYaml = (faq || []).map((f) => `  - q: "${escapeYaml(f.q)}"\n    a: "${escapeYaml(f.a)}"`).join('\n');
  const relatedYaml = (related || []).map((r) => `  - id: "${r.slug}"`).join('\n');
  return `---
title: "${escapeYaml(title)}"
description: "${escapeYaml(description)}"
pubDate: ${pubDate}
category: "${category}"
draft: ${draft ? 'true' : 'false'}
faq:
${faqYaml || '  - q: "Placeholder"\n    a: "Placeholder"'}
related:${relatedYaml ? '\n' + relatedYaml : ' []'}
---`;
}

function escapeYaml(s) {
  if (!s) return '';
  return String(s).replace(/"/g, '\\"').replace(/\n/g, ' ').slice(0, 200);
}

function renderPriceTable(prices) {
  const rows = (prices || []).slice(0, 6).map((p) =>
    `| ${p.platform} ${escapeMd(p.name)} | Rp${p.price.toLocaleString('id-ID')} | Rp${p.priceReseller.toLocaleString('id-ID')} | ${p.min.toLocaleString('id-ID')} |`,
  ).join('\n');
  return `| Layanan | Harga member/1k | Harga reseller/1k | Min order |
| --- | --- | --- | --- |
${rows}`;
}

function renderSafetyCallout() {
  return `> **Tips aman pakai SMM panel**: (1) Pilih layanan gradual refill — follower naik bertahap, bukan sekaligus, jadi lebih natural. (2) Jangan beli followers saat akun masih baru (<3 bulan) — algoritma deteksi lebih ketat. (3) Hindari spam massal — maksimal 1-2x order per minggu per akun. (4) Cek garansi refill sebelum bayar — layanan tanpa refill = risiko tinggi.`;
}

function renderCtaBlock() {
  return `> **Mau langsung cek harganya?** Daftar reseller Socio.id — Rp50.000 include saldo Rp20.000 langsung jalan + harga reseller lebih murah di semua 8.270 layanan Instagram, TikTok, YouTube, Telegram, Spotify & SEO. → [Cek harga & pesan sekarang](https://app.socio.id/daftar?mode=reseller)`;
}

function escapeMd(s) {
  if (!s) return '';
  return String(s).replace(/[|]/g, '\\|').replace(/\n/g, ' ').slice(0, 100);
}

function stripFaqSection(body) {
  return body.replace(/##\s*FAQ[\s\S]*$/i, '').trimEnd();
}

function injectAfterFirstH2(body, table) {
  const m = body.match(/^##\s+[^\n]+\n([\s\S]*?)(?=\n## |\n*$)/);
  if (!m) return body + '\n\n' + table;
  const firstH2End = m.index + m[0].length;
  return body.slice(0, firstH2End) + '\n\n' + table + '\n\n' + body.slice(firstH2End);
}

/**
 * Validasi assembled MDX — gates spec §2.
 */
export function validateMdx(content, keyword) {
  const errors = [];
  if (!content || !content.startsWith('---')) errors.push('No frontmatter');

  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!fmMatch) return { ok: false, errors: ['Invalid frontmatter structure'] };
  const fm = fmMatch[1];
  const body = fmMatch[2];

  const t = fm.match(/^title:\s*"?(.+?)"?\s*$/m);
  const title = t ? t[1].replace(/^"|"$/g, '') : '';
  if (!title) errors.push('Missing title');
  else if (title.length > 70) errors.push(`Title too long (${title.length}/70)`);

  const d = fm.match(/^description:\s*"?(.+?)"?\s*$/m);
  const desc = d ? d[1].replace(/^"|"$/g, '') : '';
  if (!desc) errors.push('Missing description');
  else if (desc.length > 160) errors.push(`Description too long (${desc.length}/160)`);

  const faqCount = (fm.match(/^\s+- q:/gm) || []).length;
  if (faqCount !== 5) errors.push(`FAQ count = ${faqCount} (expected 5)`);

  const words = body.split(/\s+/).filter(Boolean).length;
  if (words < 850) errors.push(`Body too short (${words}/850)`);
  if (words > 1400) errors.push(`Body too long (${words}/1400)`);

  const h2Count = (body.match(/^##\s/gm) || []).length;
  if (h2Count < 3 || h2Count > 5) errors.push(`H2 count = ${h2Count} (expected 3-5)`);

  // Accept both relative `/(beli|smm-panel|blog|layanan|reseller)` and absolute
  // `https://socio.id/(beli|smm-panel|blog|layanan|reseller)` internal links.
  const linkRe = new RegExp('\\[([^\\]]+)\\]\\(((?:https:\\/\\/socio\\.id)?\\/(?:beli|smm-panel|blog|layanan|reseller)[^\\)]*)\\)', 'g');
  const internalLinks = (body.match(linkRe) || []).length;
  if (internalLinks < 3) errors.push(`Internal links = ${internalLinks} (min 3)`);

  if (!body.includes('app.socio.id/daftar')) errors.push('Missing CTA');

  const firstWords = body.slice(0, 200).toLowerCase();
  const kwFirst = (keyword || '').toLowerCase().split(/\s+/)[0];
  if (kwFirst && !firstWords.includes(kwFirst)) errors.push(`Definition missing keyword "${kwFirst}"`);

  if (/[💸🤖🚀💬✨🎯📈♻⚡👑♾]/u.test(body)) errors.push('Emoji found');
  if (/\d+\s*%\s*(lebih murah|diskon|off)/i.test(body)) errors.push('Fabricated % discount');

  return { ok: errors.length === 0, errors, title, desc, faqCount, h2Count, words, internalLinks };
}

/**
 * Derive meta (title + description) dari output LLM (heuristic + template).
 */
export function deriveMeta({ keyword, llmBody, category }) {
  const valueProps = ['Cara Aman & Harga 2026', 'Panduan Lengkap', 'Harga Termurah 2026', 'Cara Aman 2026'];
  const hash = (keyword || '').split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  const vp = valueProps[hash % valueProps.length];
  let title = `${capitalize(keyword || 'smm panel')}: ${vp}`;
  if (title.length > 70) title = title.slice(0, 67) + '...';

  const firstSentence = (llmBody || '').split(/[.!?]/)[0] || '';
  let description = firstSentence.trim().slice(0, 130);
  if (description.length < 80) {
    description = `Panduan ${keyword} untuk SMM panel Indonesia. Harga real, cara pakai, dan tips aman dari data terbaru 2026.`;
  }
  if (description.length > 160) description = description.slice(0, 157) + '...';

  return { title, description, category };
}

function capitalize(s) {
  return s.split(/\s+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

// === GENERATE.MJS EXTRACT MARKERS ===
// Marker `// @end` di akhir setiap function body — generate.mjs pakai ini
// untuk extract body tanpa harus parse nested template literal/complex JS.
// Format: baris kosong lalu `// @end` tepat sebelum penutup `}`.
// @end:buildUserPrompt

// @end:parseOutput

// @end:assembleMdx

// @end:deriveMeta

// @end:validateMdx